POST http://localhost:8080/admin/register HTTP/1.1
Content-Type: application/json

{
    "email" : "muruudliinmodniimuchir@gmail.com",
    "password" : "clickclickboom"
}

###
POST http://localhost:8080/admin/login HTTP/1.1
Content-Type: application/json

{
    "email" : "muruudliinmod@gmail.com",
    "password" : "clickclickboom"
}

###
