GET http://localhost:8081/users HTTP/1.1
Content-Type: application/json

###
# ! ID gaar
GET http://localhost:8081/user?id=641147d1852af0c99a1d24e7 HTTP/1.1
Content-Type: application/json

###


# ? Maileer haisan
GET http://localhost:8081/userByMail?email=blackdragon@gmail.com HTTP/1.1
Content-Type: application/json

###
# ? findbyuseremail
GET http://localhost:8081/userByMail?email=greendragon@gmail.com HTTP/1.1
Content-Type: application/json

###

POST http://localhost:8081/user HTTP/1.1
Content-Type: application/json

{
    "name" : "Rony",
    "email" : "bluedragon@gmail.com",
    "createdOn" : "2010-01-01"
}

###

DELETE  http://localhost:8081/users HTTP/1.1
Content-Type: application/json

    {
        "_id" : "64126df1b921801dbddb7a71"
    }

###


PUT http://localhost:8081/updateUser?email=reddragon@gmail.com HTTP/1.1
Content-Type: application/json

###