POST http://localhost:8080/todo/create HTTP/1.1
Content-Type: application/json


    {
        "name" : "Washing Dishes",
        "checked" : false,
        "category" : "641935a6c349df07eabe91b6"
    }


###

PUT http://localhost:8080/todo/update HTTP/1.1
Content-Type: application/json

[
    {
        "checked" : true
    },
    {
        "name" : "Bathing KIDs"
    }
]
###

GET http://localhost:8080/todo/list HTTP/1.1
Content-Type: application/json


###

DELETE http://localhost:8080/todo/delete HTTP/1.1
Content-Type: application/json

{
    "checked" : false
}

###

